image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-maven
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
